In [1]:
#2. Implementation of relationship between pixels.

import numpy as np

a = np.array([[11, 2, 4, 8, 7],
              [2, 34, 12, 45, 67],
              [11, 77, 55, 26, 45],
              [12, 23, 45, 6, 21],
              [10, 9, 17, 16, 3]])

print("a =", a)
b = int(input("\nEnter the row (0 to 4): "))
c = int(input("\nEnter the column (0 to 4): "))
print("\nElement: ", a[b, c])

N4 = []
if b + 1 < 5:
    N4.append(a[b + 1, c])
if b - 1 >= 0:
    N4.append(a[b - 1, c])
if c + 1 < 5:
    N4.append(a[b, c + 1])
if c - 1 >= 0:
    N4.append(a[b, c - 1])
print("\nNeighbours of N4: ", N4)

Nd = []
if b + 1 < 5 and c + 1 < 5:
    Nd.append(a[b + 1, c + 1])
if b + 1 < 5 and c - 1 >= 0:
    Nd.append(a[b + 1, c - 1])
if b - 1 >= 0 and c + 1 < 5:
    Nd.append(a[b - 1, c + 1])
if b - 1 >= 0 and c - 1 >= 0:
    Nd.append(a[b - 1, c - 1])
print("\nDiagonal Neighbours Nd: ", Nd)

N8 = []
if b + 1 < 5:
    N8.append(a[b + 1, c])
if b - 1 >= 0:
    N8.append(a[b - 1, c])
if c + 1 < 5:
    N8.append(a[b, c + 1])
if c - 1 >= 0:
    N8.append(a[b, c - 1])
if b + 1 < 5 and c + 1 < 5:
    N8.append(a[b + 1, c + 1])
if b + 1 < 5 and c - 1 >= 0:
    N8.append(a[b + 1, c - 1])
if b - 1 >= 0 and c + 1 < 5:
    N8.append(a[b - 1, c + 1])
if b - 1 >= 0 and c - 1 >= 0:
    N8.append(a[b - 1, c - 1])
print("\nNeighbours of N8: ", N8)


a = [[11  2  4  8  7]
 [ 2 34 12 45 67]
 [11 77 55 26 45]
 [12 23 45  6 21]
 [10  9 17 16  3]]

Element:  55

Neighbours of N4:  [45, 12, 26, 77]

Diagonal Neighbours Nd:  [6, 23, 45, 34]

Neighbours of N8:  [45, 12, 26, 77, 6, 23, 45, 34]


In [4]:
from PIL import Image
import numpy as np

# Open an image file
image_path = "images/rose.jpeg"
img = Image.open(image_path)

# Convert the image to a NumPy array
a = np.array(img)


b = int(input("\nEnter the row (0 to 4): "))
c = int(input("\nEnter the column (0 to 4): "))
print("\nElement: ", a[b, c])

N4 = []
if b + 1 < 5:
    N4.append(a[b + 1, c])
if b - 1 >= 0:
    N4.append(a[b - 1, c])
if c + 1 < 5:
    N4.append(a[b, c + 1])
if c - 1 >= 0:
    N4.append(a[b, c - 1])
print("\nNeighbours of N4: ", N4)

Nd = []
if b + 1 < 5 and c + 1 < 5:
    Nd.append(a[b + 1, c + 1])
if b + 1 < 5 and c - 1 >= 0:
    Nd.append(a[b + 1, c - 1])
if b - 1 >= 0 and c + 1 < 5:
    Nd.append(a[b - 1, c + 1])
if b - 1 >= 0 and c - 1 >= 0:
    Nd.append(a[b - 1, c - 1])
print("\nDiagonal Neighbours Nd: ", Nd)

N8 = []
if b + 1 < 5:
    N8.append(a[b + 1, c])
if b - 1 >= 0:
    N8.append(a[b - 1, c])
if c + 1 < 5:
    N8.append(a[b, c + 1])
if c - 1 >= 0:
    N8.append(a[b, c - 1])
if b + 1 < 5 and c + 1 < 5:
    N8.append(a[b + 1, c + 1])
if b + 1 < 5 and c - 1 >= 0:
    N8.append(a[b + 1, c - 1])
if b - 1 >= 0 and c + 1 < 5:
    N8.append(a[b - 1, c + 1])
if b - 1 >= 0 and c - 1 >= 0:
    N8.append(a[b - 1, c - 1])
print("\nNeighbours of N8: ", N8)



Element:  [15  8  2]

Neighbours of N4:  [array([17,  8,  1], dtype=uint8), array([17,  8,  1], dtype=uint8)]

Diagonal Neighbours Nd:  [array([19,  9,  0], dtype=uint8)]

Neighbours of N8:  [array([17,  8,  1], dtype=uint8), array([17,  8,  1], dtype=uint8), array([19,  9,  0], dtype=uint8)]
